name: CI

on: [push, pull_request]

jobs:
  build-Linux:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get --no-install-recommends install \
            catch2 \
            libfreetype6-dev \
            libglew-dev \
            libglm-dev \
            libmsgpack-dev \
            libnetcdf-dev \
            libpng-dev \
            libxml2-dev

    - name: Install collada2gltf
      run: |
        wget -nv https://anaconda.org/schrodinger/collada2gltf/2.1.4/download/linux-64/collada2gltf-2.1.4-h6bb024c_0.tar.bz2
        sudo tar xf collada2gltf-*.tar.bz2 -C / bin/collada2gltf

    - name: Get additional sources
      run: |
        git clone --depth 1 https://github.com/rcsb/mmtf-cpp.git
        cp -R mmtf-cpp/include/* include/

    - name: Build
      run: |
        pip install --upgrade pip
        pip install -v --config-settings testing=True '.[dev]'
      env:
        DEBUG: 1

    - name: Test
      run: |
        pymol -ckqy testing/testing.py --run all


  build-Windows:

    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.8

    - name: Set Python version
      run: pixi add "python==${{ matrix.python-version }}.*"

    - name: Get additional sources
      shell: bash
      run: |
        PIXI_PREFIX="$(pixi info --json | python3 -c 'import sys,json; print(json.loads(sys.stdin.read())["environments_info"][0]["prefix"])')"
        git clone --depth 1 https://github.com/rcsb/mmtf-cpp.git
        cp -R mmtf-cpp/include/* "${PIXI_PREFIX}/Library/include/"
        git clone --depth 1 --single-branch --branch cpp_master https://github.com/msgpack/msgpack-c.git
        cp -R msgpack-c/include/* "${PIXI_PREFIX}/Library/include/"

    - name: Build PyMOL
      run: pixi run pip install -v --config-settings testing=True .[dev]

    - name: Test
      run: pixi run pymol -ckqy testing\testing.py --run all


  build-MacOS:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.8

    - name: Set Python version
      run: pixi add "python==${{ matrix.python-version }}.*"

    - name: Get additional sources
      run: |
        PIXI_PREFIX="$(pixi info --json | python3 -c 'import sys,json; print(json.loads(sys.stdin.read())["environments_info"][0]["prefix"])')"
        git clone --depth 1 https://github.com/rcsb/mmtf-cpp.git
        cp -R mmtf-cpp/include/* "${PIXI_PREFIX}/include/"
        git clone --depth 1 --single-branch --branch cpp_master https://github.com/msgpack/msgpack-c.git
        cp -R msgpack-c/include/* "${PIXI_PREFIX}/include/"

    - name: Build PyMOL
      run: pixi run bash -c 'MACOSX_DEPLOYMENT_TARGET=12.0 pip install -v --config-settings testing=True ".[dev]"'

    - name: Test
      run: pixi run pymol -ckqy testing/testing.py --run all

